sudo: required

dist: trusty

language: node_js

node_js:
  - "10"

env:
  matrix:
    - RUBY_VERSION=2.4

before_install:
  - rvm use $RUBY_VERSION --install --binary --fuzzy

install:
  - npm install
  - bundle install --retry 3 --clean --path vendor/bundle

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor/bundle
